// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"smp/config"
	"smp/db"
	"smp/handler"
	"smp/repository"
	"smp/service"
)

// Injectors from wire.go:

func InitializeHandlers() *Handlers {
	configConfig := config.LoadConfig()
	pgDb := db.ProvidePgDb(configConfig)
	pool := db.ProvidePool(pgDb)
	userRepo := repository.NewUserRepo(pool)
	client := db.ProvideRedis(configConfig)
	userService := service.NewUserService(userRepo, client)
	userHandler := handler.NewUserHandler(userService)
	classroomRepo := repository.NewClassroomRepo(pool)
	classroomService := service.NewClassroomService(classroomRepo)
	classroomHandler := handler.NewClassroomHandler(classroomService)
	handlers := &Handlers{
		UserHandler:      userHandler,
		ClassroomHandler: classroomHandler,
	}
	return handlers
}
