// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"smp/config"
	"smp/db"
	"smp/handler"
	"smp/repository"
	"smp/service"
)

// Injectors from wire.go:

func InitializeHandlers() *Handlers {
	configConfig := config.LoadConfig()
	pgDb := db.ProvidePgDb(configConfig)
	pool := db.ProvidePool(pgDb)
	userRepo := repository.NewUserRepo(pool)
	client := db.ProvideRedis(configConfig)
	userService := service.NewUserService(userRepo, client)
	userHandler := handler.NewUserHandler(userService, pool)
	classroomRepo := repository.NewClassroomRepo(pool)
	classroomService := service.NewClassroomService(classroomRepo)
	classroomHandler := handler.NewClassroomHandler(classroomService, pool)
	eventRepo := repository.NewEventRepository(pool)
	eventService := service.NewEventService(eventRepo)
	eventHandler := handler.NewEventHandler(eventService, pool)
	salaryRepository := repository.NewSalaryRepository(pool)
	salaryService := service.NewSalaryService(salaryRepository)
	salaryHandler := handler.NewSalaryHandler(salaryService)
	timetableRepository := repository.NewTimetableRepository(pool)
	timetableService := service.NewTimetableService(timetableRepository)
	timetableHandler := handler.NewTimetableHandler(timetableService)
	marksRepository := repository.NewMarksRepository(pool)
	marksService := service.NewMarksService(marksRepository)
	marksHandler := handler.NewMarksHandler(marksService)
	adminDashboardRepository := repository.NewDashboardRepository(pool)
	dashboardService := service.NewDashboardService(adminDashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	teacherDashboardRepository := repository.NewTeacherDashboardRepository(pool)
	teacherDashboardService := service.NewTeacherDashboardService(teacherDashboardRepository)
	teacherDashboardHandler := handler.NewTeacherDashboardHandler(teacherDashboardService)
	handlers := &Handlers{
		UserHandler:             userHandler,
		ClassroomHandler:        classroomHandler,
		EventHandler:            eventHandler,
		SalaryHandler:           salaryHandler,
		TimetableHandler:        timetableHandler,
		MarksHandler:            marksHandler,
		DashboardHandler:        dashboardHandler,
		TeacherDashboardHandler: teacherDashboardHandler,
	}
	return handlers
}
