// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"smp/config"
	"smp/db"
	"smp/handler"
	"smp/repository"
	"smp/service"
)

// Injectors from wire.go:

func InitializeHandlers() *Handlers {
	configConfig := config.LoadConfig()
	pgDb := db.ProvidePgDb(configConfig)
	pool := db.ProvidePool(pgDb)
	userRepo := repository.NewUserRepo(pool)
	client := db.ProvideRedis(configConfig)
	userService := service.NewUserService(userRepo, client)
	userHandler := handler.NewUserHandler(userService)
	classroomRepo := repository.NewClassroomRepo(pool)
	classroomService := service.NewClassroomService(classroomRepo)
	classroomHandler := handler.NewClassroomHandler(classroomService)
	eventRepo := repository.NewEventRepository(pool)
	eventService := service.NewEventService(eventRepo)
	eventHandler := handler.NewEventHandler(eventService)
	salaryRepository := repository.NewSalaryRepository(pool)
	salaryService := service.NewSalaryService(salaryRepository)
	salaryHandler := handler.NewSalaryHandler(salaryService)
	timetableRepository := repository.NewTimetableRepository(pool)
	timetableService := service.NewTimetableService(timetableRepository)
	timetableHandler := handler.NewTimetableHandler(timetableService)
	handlers := &Handlers{
		UserHandler:      userHandler,
		ClassroomHandler: classroomHandler,
		EventHandler:     eventHandler,
		SalaryHandler:    salaryHandler,
		TimetableHandler: timetableHandler,
	}
	return handlers
}
